language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -t vkas288/docker-react -f Dockerfile.dev .

script:
  - docker run vkas288/docker-react npm run test -- --coverage